import Link from "next/link";
import { prisma, PROGRAM_ID, calculateReadinessScore } from "@missionthread/core";
import { requireSession } from "@/lib/auth-helpers";
import { StatusBadge } from "@/components/status-badge";
import { PrintButton } from "./print-button";

interface VerificationGapJson {
  requirementId: string;
  category: string;
  summary: string;
}

function asStringArray(value: unknown): string[] {
  return Array.isArray(value)
    ? value.filter((item): item is string => typeof item === "string")
    : [];
}

function asVerificationGaps(value: unknown): VerificationGapJson[] {
  if (!Array.isArray(value)) return [];
  return value.filter(
    (item): item is VerificationGapJson =>
      typeof item === "object" &&
      item !== null &&
      "requirementId" in item &&
      "category" in item &&
      "summary" in item,
  );
}

function formatMoney(amount: unknown): string {
  return `USD ${Number(amount).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
}

export default async function ReadinessBriefingPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  // Every authenticated role may view a completed briefing.
  await requireSession();
  const { id: analysisRunId } = await params;

  const succeeded = await prisma.impactAnalysis.findFirst({
    where: { analysisRunId, status: "SUCCEEDED" },
    include: {
      mitigationOptions: { orderBy: { optionIndex: "asc" } },
      sourceReferences: { orderBy: [{ recordType: "asc" }, { recordId: "asc" }] },
      programEvent: { include: { component: true, supplier: true } },
    },
  });

  // A pending or failed run has no briefing to show — never render a
  // fabricated "completed" view for one. Distinguishing "run doesn't
  // exist" from "run exists but never succeeded" isn't necessary here: both
  // cases correctly show this same safe, non-briefing state, with a link
  // back to the workspace (which does show the real, safe failure detail).
  if (!succeeded) {
    return (
      <section className="mt-6 rounded-lg border border-border bg-surface p-6">
        <h1 className="text-lg font-semibold text-foreground">Readiness briefing unavailable</h1>
        <p className="mt-2 text-sm text-muted">
          This analysis run has no successful attempt yet, so no readiness briefing can be shown.
        </p>
        <Link
          href={`/programs/edgelink-x/analyses/${encodeURIComponent(analysisRunId)}`}
          className="mt-4 inline-block text-sm font-medium text-accent hover:underline"
        >
          View analysis workspace →
        </Link>
      </section>
    );
  }

  const readinessResult = await calculateReadinessScore(PROGRAM_ID);
  const event = succeeded.programEvent;
  const recommended = succeeded.mitigationOptions.find((option) => option.isRecommended);
  const risks = succeeded.sourceReferences.filter((ref) => ref.recordType === "RISK");

  return (
    <>
      <div className="flex flex-wrap items-start justify-between gap-4 print:hidden">
        <Link
          href={`/programs/edgelink-x/analyses/${encodeURIComponent(analysisRunId)}`}
          className="text-sm font-medium text-accent hover:underline"
        >
          ← Back to analysis workspace
        </Link>
        <PrintButton />
      </div>

      <div className="mt-6 rounded-lg border border-border bg-surface p-8 print:border-none print:p-0 print:shadow-none">
        <header className="border-b border-border pb-4">
          <h1 className="text-xl font-semibold text-foreground">EdgeLink-X readiness briefing</h1>
          <p className="mt-1 text-sm text-muted">
            Event <span className="font-mono">{event.id}</span> (
            {event.eventType.replaceAll("_", " ")})
            {event.component ? ` — ${event.component.name}` : ""}
            {event.supplier ? ` — ${event.supplier.name}` : ""}
          </p>
          <dl className="mt-3 flex flex-wrap gap-x-6 gap-y-1 text-xs text-muted">
            <span>
              Trace ID <span className="font-mono">{succeeded.traceId}</span>
            </span>
            <span>
              Confidence <StatusBadge status={succeeded.confidence ?? "MEDIUM"} />
            </span>
            <span>
              Generated by {succeeded.provider ?? "unknown"} ({succeeded.aiMode} mode)
            </span>
          </dl>
          <p className="mt-3 rounded-md border border-warning/30 bg-warning/10 px-3 py-2 text-xs text-warning">
            The mitigation options below are AI-generated proposals pending human Program Manager
            review — none has been approved, rejected, or applied.
          </p>
        </header>

        <section className="mt-4">
          <h2 className="text-sm font-semibold text-foreground">Executive summary</h2>
          <p className="mt-2 text-sm text-foreground">{succeeded.executiveSummary}</p>
          <h2 className="mt-4 text-sm font-semibold text-foreground">Mission impact</h2>
          <p className="mt-2 text-sm text-foreground">{succeeded.missionImpact}</p>
        </section>

        <section className="mt-4 grid grid-cols-3 gap-4 border-t border-border pt-4 text-sm">
          <div>
            <div className="text-xs tracking-wide text-muted uppercase">Program readiness</div>
            <div className="mt-1 font-medium text-foreground">
              {readinessResult.ok ? `${readinessResult.data.totalScore}/100` : "Unavailable"}
            </div>
          </div>
          <div>
            <div className="text-xs tracking-wide text-muted uppercase">Schedule exposure</div>
            <div className="mt-1 font-medium text-foreground">
              {succeeded.scheduleExposureDays !== null
                ? `${succeeded.scheduleExposureDays} day(s)`
                : "Unknown"}
            </div>
          </div>
          <div>
            <div className="text-xs tracking-wide text-muted uppercase">Budget exposure</div>
            <div className="mt-1 font-medium text-foreground">
              {succeeded.budgetExposureAmount !== null
                ? formatMoney(succeeded.budgetExposureAmount)
                : "Unknown"}
            </div>
          </div>
        </section>

        <section className="mt-4 border-t border-border pt-4">
          <h2 className="text-sm font-semibold text-foreground">Key verification gaps</h2>
          {asVerificationGaps(succeeded.verificationGaps).length === 0 ? (
            <p className="mt-2 text-sm text-muted">No verification gaps identified.</p>
          ) : (
            <ul className="mt-2 list-disc pl-5 text-sm text-foreground">
              {asVerificationGaps(succeeded.verificationGaps).map((gap, index) => (
                <li key={index}>
                  <span className="font-mono text-xs text-muted">{gap.requirementId}</span> —{" "}
                  {gap.category}: {gap.summary}
                </li>
              ))}
            </ul>
          )}
        </section>

        <section className="mt-4 border-t border-border pt-4">
          <h2 className="text-sm font-semibold text-foreground">Relevant risks</h2>
          {risks.length === 0 ? (
            <p className="mt-2 text-sm text-muted">No risks cited in this analysis.</p>
          ) : (
            <ul className="mt-2 list-disc pl-5 text-sm text-foreground">
              {risks.map((risk) => (
                <li key={risk.id}>
                  <span className="font-mono text-xs text-muted">{risk.recordId}</span> —{" "}
                  {risk.summary}
                </li>
              ))}
            </ul>
          )}
        </section>

        <section className="mt-4 border-t border-border pt-4">
          <h2 className="text-sm font-semibold text-foreground">Mitigation options</h2>
          <div className="mt-2 flex flex-col gap-3">
            {succeeded.mitigationOptions.map((option) => (
              <div
                key={option.id}
                className={`rounded-md border p-3 text-sm ${
                  option.isRecommended ? "border-accent bg-accent/5" : "border-border"
                }`}
              >
                <div className="flex items-center justify-between gap-2">
                  <span className="font-medium text-foreground">{option.title}</span>
                  {option.isRecommended && (
                    <span className="rounded-full bg-accent/10 px-2 py-0.5 text-xs font-medium text-accent">
                      Recommended
                    </span>
                  )}
                </div>
                <p className="mt-1 text-foreground">{option.description}</p>
                <p className="mt-1 text-xs text-muted">Tradeoffs: {option.tradeoffs}</p>
              </div>
            ))}
          </div>
          {recommended && (
            <p className="mt-3 text-sm text-foreground">
              <span className="font-medium">Recommendation:</span> {recommended.title}
            </p>
          )}
        </section>

        <section className="mt-4 border-t border-border pt-4 grid gap-4 sm:grid-cols-2">
          <div>
            <h2 className="text-xs font-semibold tracking-wide text-muted uppercase">
              Assumptions
            </h2>
            <ul className="mt-2 list-disc pl-5 text-sm text-foreground">
              {asStringArray(succeeded.assumptions).map((item, index) => (
                <li key={index}>{item}</li>
              ))}
            </ul>
          </div>
          <div>
            <h2 className="text-xs font-semibold tracking-wide text-muted uppercase">Unknowns</h2>
            <ul className="mt-2 list-disc pl-5 text-sm text-foreground">
              {asStringArray(succeeded.unknowns).map((item, index) => (
                <li key={index}>{item}</li>
              ))}
            </ul>
          </div>
        </section>

        <section className="mt-4 border-t border-border pt-4">
          <h2 className="text-xs font-semibold tracking-wide text-muted uppercase">
            Source references
          </h2>
          <ul className="mt-2 flex flex-col gap-1 text-xs text-muted">
            {succeeded.sourceReferences.map((ref) => (
              <li key={ref.id}>
                {ref.recordType} <span className="font-mono">{ref.recordId}</span> — {ref.summary}
              </li>
            ))}
          </ul>
        </section>
      </div>
    </>
  );
}
